name: Extension

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install vsce
        run: npm i -g vsce
      - name: Install dependencies and build
        run: npm install && npm run build:extension && vsce package -o extension.vsix
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "save extension"
      - name: push code to master
        run: git push origin HEAD:master
