name: Extension

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install vsce
        run: npm i -g vsce
      - name: Install dependencies and build
        run: npm install && npm run build:extension && vsce package -o extension.vsix
      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads
      - name: Step 2 - Move .vsix file to downloads folder
        run: mv extension.vsix /downloads/
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: vscode-extension
          path: downloads
