name: Extension

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install vsce
        run: npm i -g vsce
      - name: Install dependencies and build
        run: npm install && npm run build:extension && vsce package
      - name: Move package file to parent
        run: mv /home/runner/work/testing-vscode/testing-vscode/extension-test-trial2-0.0.13.vsix ..
      - name: Publish package on NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
